# Generated by Django 4.0.4 on 2022-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Nazwa uzytkownika')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dolaczenia')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Ostatnie logowanie')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('birthdate', models.DateField(verbose_name='Data urodzenia')),
                ('addr_city', models.CharField(max_length=30, verbose_name='Miasto')),
                ('addr_street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('addr_post_code', models.CharField(max_length=25, verbose_name='Kod pocztowy')),
                ('mobile_nr', models.CharField(max_length=15, verbose_name='Nr telefonu')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrator')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Pracownik')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Glowny administrator')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Uzytkownik',
                'verbose_name_plural': 'Uzytkownicy',
            },
        ),
    ]
