# Generated by Django 4.0.4 on 2022-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Username')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Join date')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birthdate', models.DateField(verbose_name='Date of birth')),
                ('addr_city', models.CharField(max_length=30, verbose_name='City')),
                ('addr_street', models.CharField(max_length=100, verbose_name='Street')),
                ('addr_post_code', models.CharField(max_length=25, verbose_name='Post code')),
                ('mobile_nr', models.CharField(max_length=15, verbose_name='Mobile')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
