# Generated by Django 4.0.4 on 2022-05-17 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(verbose_name='Cena Bazowa')),
            ],
            options={
                'verbose_name': 'Cena Bazowa',
                'verbose_name_plural': 'Cena Bazowa',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Numer rejestracyjny')),
                ('year_of_production', models.IntegerField(verbose_name='Rok produkcji')),
                ('rating', models.FloatField(verbose_name='Ocena')),
                ('number_of_seats', models.IntegerField(verbose_name='Ilość miejsc')),
                ('engine_type', models.CharField(choices=[('Benzynowy', 'Benzynowy'), ('Diesel', 'Diesel'), ('Elektryczny', 'Elektryczny'), ('Hybryda', 'Hybryda')], max_length=20, verbose_name='Rodzaj silnika')),
                ('engine_power', models.IntegerField(verbose_name='Moc')),
                ('color', models.CharField(max_length=50, verbose_name='Kolor')),
                ('car_mileage', models.IntegerField(verbose_name='Przebieg')),
                ('car_image', models.ImageField(upload_to='images/cars', verbose_name='Zdjęcie')),
                ('gearbox_type', models.CharField(choices=[('Automatyczna', 'Automatyczna'), ('Manualna', 'Manualna')], max_length=15, verbose_name='Skrzynia biegów')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True, verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('client_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nr telefonu')),
                ('client_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Imie')),
                ('client_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nazwisko')),
                ('car_plate_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer rejestracyjny')),
                ('car_brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marka')),
                ('car_model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model')),
                ('rent_cost', models.IntegerField(blank=True, null=True, verbose_name='Koszt wynajmu')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('return_date', models.DateField(verbose_name='Zwrot')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Powstanie zamówienia')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Edytowane')),
                ('status', models.CharField(choices=[('Aktywny', 'Aktywny'), ('Historia', 'Historia')], default='Aktywny', max_length=10, verbose_name='Status')),
                ('base_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.baseprice', verbose_name='Cena bazowa')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.car', verbose_name='Samochód')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Klient')),
            ],
            options={
                'verbose_name': 'Log Wypozyczenia',
                'verbose_name_plural': 'Logi Wypozyczen',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modele',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carmodel', verbose_name='Model'),
        ),
    ]
