# Generated by Django 4.0.4 on 2022-04-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('carrentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustom',
            new_name='User',
        ),
    ]
