# Generated by Django 4.0.4 on 2022-05-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='car_plate_nr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_mobile',
        ),
    ]
