# Generated by Django 4.0.4 on 2022-04-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0003_rename_user_usercustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'CarBrands',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'CarModels',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('year_of_production', models.IntegerField(verbose_name='Year of production')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('number_of_seats', models.IntegerField(verbose_name='Number of seats')),
                ('engine_type', models.CharField(choices=[('p', 'Petrol'), ('d', 'Diesel'), ('e', 'Electric'), ('h', 'Hybrid')], max_length=20, verbose_name='Engine type')),
                ('engine_power', models.IntegerField(verbose_name='Engine power')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('car_mileage', models.IntegerField(verbose_name='Car mileage')),
                ('car_image', models.ImageField(upload_to='images/cars', verbose_name='Image')),
                ('gearbox_type', models.CharField(choices=[('a', 'Automatic'), ('m', 'Manual')], max_length=10, verbose_name='Gearbox')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carmodel')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
