# Generated by Django 4.0.3 on 2022-05-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0003_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprice',
            options={'verbose_name': 'Cena Bazowa', 'verbose_name_plural': 'Ceny Bazowe'},
        ),
    ]
