# Generated by Django 4.0.4 on 2022-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0005_alter_car_options_alter_carbrand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'verbose_name': 'Uzytkownik', 'verbose_name_plural': 'Uzytkownicy'},
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='addr_city',
            field=models.CharField(max_length=30, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='addr_post_code',
            field=models.CharField(max_length=25, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='addr_street',
            field=models.CharField(max_length=100, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='birthdate',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Glowny administrator'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dolaczenia'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnie logowanie'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='mobile_nr',
            field=models.CharField(max_length=15, verbose_name='Nr telefonu'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nazwa uzytkownika'),
        ),
    ]
