# Generated by Django 4.0.3 on 2022-05-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0006_profile'),
        ('carrentapp', '0007_rename_model_car_car_model'),
    ]

    operations = [
    ]
