# Generated by Django 4.0.4 on 2022-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0008_merge_0006_profile_0007_rename_model_car_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(verbose_name='Cena Bazowa')),
            ],
            options={
                'verbose_name': 'Cena Bazowa',
                'verbose_name_plural': 'Cena Bazowa',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
