# Generated by Django 4.0.4 on 2022-05-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0009_baseprice_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('client_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nr telefonu')),
                ('client_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Imie')),
                ('client_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nazwisko')),
                ('car_plate_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer rejestracyjny')),
                ('car_brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marka')),
                ('car_model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model')),
                ('rent_cost', models.IntegerField(blank=True, null=True, verbose_name='Koszt wynajmu')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('return_date', models.DateField(verbose_name='Zwrot')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Powstanie zamówienia')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Edytowane')),
                ('status', models.CharField(choices=[('Aktywny', 'Aktywny'), ('Historia', 'Historia')], max_length=10, verbose_name='Status')),
                ('base_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.baseprice')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Wypozyczenia',
                'verbose_name_plural': 'Logi Wypozyczen',
            },
        ),
    ]
