# Generated by Django 4.0.4 on 2022-05-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aktywny', 'Aktywny'), ('Historia', 'Historia')], default='Aktywny', max_length=10, verbose_name='Status'),
        ),
    ]
