# Generated by Django 4.0.4 on 2022-05-11 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carmodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='order',
            name='base_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.baseprice', verbose_name='Cena bazowa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrentapp.car', verbose_name='Samochód'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Klient'),
        ),
    ]
